namespace AutoSig.Domain.Models;

/// <summary>Represents the type of transaction the Strategist wants to execute.</summary>
public enum ProposalType
{
    SolTransfer,
    SplTokenTransfer,
    SplTokenMint
}

/// <summary>
/// The core immutable proposal created by the Strategist Agent.
/// Flows through the system from Strategist → RiskManager → Executor.
/// </summary>
public sealed record TradeProposal
{
    public Guid Id { get; init; } = Guid.NewGuid();
    public DateTime CreatedAt { get; init; } = DateTime.UtcNow;

    /// <summary>The symbolic opportunity that triggered this proposal.</summary>
    public required string Opportunity { get; init; }

    /// <summary>What type of on-chain action this proposal represents.</summary>
    public required ProposalType Type { get; init; }

    /// <summary>Amount in lamports (SOL) or base units (SPL).</summary>
    public required ulong AmountLamports { get; init; }

    /// <summary>Destination wallet or program address (Base58).</summary>
    public required string DestinationAddress { get; init; }

    /// <summary>For SPL transfers/mints – the token's mint address. Null for pure SOL transfers.</summary>
    public string? MintAddress { get; init; }

    /// <summary>Natural language rationale generated by the Strategist LLM.</summary>
    public required string Rationale { get; init; }

    /// <summary>Estimated risk level as self-assessed by the Strategist (0.0 = no risk, 1.0 = extreme risk).</summary>
    public required double SelfAssessedRisk { get; init; }
}
